# -*- coding: utf-8 -*-
"""Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dVZU5dWRPEhfNCvUPt_RbAQLXglJRyft
"""

print("Hello data type")

"""**List data type**
  1.Append
  2.clear
  3.Copy
  4.Count
  5.Extend
  6.Index
  7.Insert
  8.Pop
  9.Remove
  10.Reverse
  11.Sort
"""

lst =[ "Pujitha","python",123,12.78,[2,4,6] ]



# 1.Append
lst.append("letupgrade")

a=[1,2,3,4,5]

# 2.Copy
a.clear()

print(a)

# 3.Copy
c=[6,7,8,9]
b=c.copy()

print(c)
print(b)

# 4.Count
d=[4,5,6,6,5,4]
e=[7,8,9,9,8,7]

print (d.count(6))
print (e.count(9))

# 5.Extend
d.extend([1,2,3])
print(d)

# 6.Index
print(c.index(8))

# 7.Insert
x=["hi","how"]
print(x)
x.insert(2," are you")
print(x)

# 8.Pop
x=["hi","how"]
print(x)
x.pop(0)
print(x)

# 9.Remove
y=["hello","bye"]
print(y)
y.remove("bye")
print(y)

# 10.Reverse
z=["p","q","r","s","t"]
print(z)
z.reverse()
print(z)

# 11.sort
y=[22,545,67,43,]
y.sort()
print(y)

"""**Dictionary**"""

dit ={"Name":"Pujitha","Age":"16","Phone no":12345}
dit
dit["Name"]

dit["School"]="Laurel"
dit

"""**Sets**"""

st ={"Data","structure",9,8,7,6,}
print(st)

#Issubset
st1={"Data","structure"}
st1.issubset(st)

#Issuperset
print(st.issuperset(st1))
print(st1.issuperset(st))

#Difference
print(st.difference(st1))
print(st1.difference(st))

#Difference_update
i={"Good","night","sweet","dream"}
j={"Good","night"}
i.difference_update(j)
print(i)

#Discard
i.discard("sweet")
print(i)

#Intersection
print(i.intersection(j))
print(i)

# Intersection_update
u={"what","are","thinking"}
v={"are","thinking","about","me"}
u.intersection_update(v)
print ("u:",u)
print ("v:",v)

# Isdisjoint
u.isdisjoint(v)

"""**tuple**"""

tub =("ishana","reaper","@","gmail","com")
tub.count("@")

tub.index("reaper")

"""**String**"""

str ="I brought"
print (str)
str1="An Iphone"
print (str1)